CREATE TABLE [dbo].[ChatRoomMembers]
(
	[ChatRoomId] INT NOT NULL,
	[UserId] INT NOT NULL

	CONSTRAINT [FK_CHATROOM_ID] FOREIGN KEY ([ChatRoomId]) REFERENCES [ChatRooms]([Id])
		ON DELETE CASCADE,
	CONSTRAINT [FK_USER_ID]		FOREIGN KEY ([UserId])	REFERENCES [Users]([Id])	
		ON DELETE CASCADE	
)
