CREATE TABLE [dbo].[Notifications]
(
	[Id]			BIGINT	IDENTITY(1,1) NOT NULL,
	[Type]			INT NULL,
	[UserId]		INT NOT NULL,
	[Info]			NVARCHAR(MAX) NULL,
	[ChatRoomId]	INT NOT NULL,
	[IsSeen]		BIT DEFAULT(0) NOT NULL
	
	CONSTRAINT [PK_NOTIFICATION_ID] PRIMARY KEY([Id]),
	CONSTRAINT [FK_NOTIFICATION_USER_ID] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
		ON DELETE CASCADE,
	CONSTRAINT [FK_NOTIFICATION_CHAT_ROOM_ID] FOREIGN KEY ([ChatRoomId]) REFERENCES [ChatRooms]([Id])
		ON DELETE CASCADE	
)