CREATE PROCEDURE [dbo].[uspCreateChatRoom]
	@name			NVARCHAR(100),
	@isGroup		BIT,
	@pictureUrl		VARCHAR(MAX)
AS
	BEGIN
		BEGIN TRY
			BEGIN TRANSACTION CREATE_CHAT_ROOM
				INSERT INTO [ChatRooms] VALUES (
					@name,
					GETDATE(),
					@isGroup,
					@pictureUrl)
			COMMIT TRANSACTION CREATE_CHAT_ROOM
			RETURN SCOPE_IDENTITY()
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION CREATE_CHAT_ROOM
			RETURN 1
		END CATCH
	END