/*
* GNU General Public License Version 3.0, 29 June 2007
* Header file of errors.
* Copyright (C) 2018  David Petrosyan
* Email: david.petrosyan11100@gmail.com
* For full notice please see https://github.com/amirkhaniansev/tyche/tree/master/LICENSE.
*/

#ifndef __CONTAINER_ERROR_H__
#define __CONTAINER_ERROR_H__
/**
* exit codes start from 0x100
*/
#define SUCCESSFULLY_COMPLETED 0x100
#define VECTOR_ALLOCATION_ERROR 0x101
#define VECTOR_COMPARATOR_ERROR_IN_CONSTRUCTOR 0x102
#define VECTOR_ASSIGNER_ERROR_IN_CONSTRUCTOR 0x103
#define VECTOR_FINALIZER_ERROR_IN_CONSTRUCTOR 0x104
#define VECTOR_BASE_ALLOCATION_ERROR_IN_CONSTRUCTOR 0x105
#define VECTOR_DATASIZE_NEGATIVE 0x106
#define VECTOR_ASSIGNER_IS_NULL 0x107
#define VECTOR_ASSIGN_RIGHT_IS_NULL 0x108
#define VECTOR_BASE_ALLOCATION_ERROR_IN_ASSIGN 0x109
#define VECTOR_BASE_ALLOCATION_ERROR_IN_INSERT 0x110
#define VECTOR_HIGH_POSSITION_IN_INSERT 0x111
#define VECTOR_IS_EMPTY 0x112
#define VECTOR_ERASE_POSITION_OUT_OF_RANGE 0x113
#define VECTOR_IS_NULL 0x114
#define VECTOR_IS_CLEAR 0x115

#endif